insert_statements = {}

insert_statements['ticker_info'] = ("""
INSERT INTO `ticks`.`ticker_info`
(`sector`,
`fullTimeEmployees`,
`city`,
`operatingCashflow`,
`revenueGrowth`,
`operatingMargins`,
`ebitda`,
`targetLowPrice`,
`targetMeanPrice`,
`targetHighPrice`,
`recommendationKey`,
`recommendationMean`,
`grossProfits`,
`freeCashflow`,
`targetMedianPrice`,
`currentPrice`,
`earningsGrowth`,
`currentRatio`,
`returnOnAssets`,
`debtToEquity`,
`returnOnEquity`,
`totalCash`,
`totalDebt`,
`totalRevenue`,
`totalCashPerShare`,
`financialCurrency`,
`revenuePerShare`,
`quickRatio`,
`exchange`,
`shortName`,
`longName`,
`exchangeTimezoneName`,
`exchangeTimezoneShortName`,
`quoteType`,
`symbol`,
`annualHoldingsTurnover`,
`enterpriseToRevenue`,
`beta3Year`,
`enterpriseToEbitda`,
`52WeekChange`,
`morningStarRiskRating`,
`forwardEps`,
`revenueQuarterlyGrowth`,
`sharesOutstanding`,
`annualReportExpenseRatio`,
`totalAssets`,
`bookValue`,
`shareShort`,
`sharesPercentSharesOut`,
`heldPercentInstitutions`,
`netIncomeToCommon`,
`trailingEps`,
`lastDividendValue`,
`SandP52WeekChange`,
`priceToBook`,
`heldPercentInsiders`,
`yield`,
`mostRecentQuarter`,
`shortRatio`,
`sharesShortPreviousMonthDate`,
`floatShares`,
`beta`,
`enterpriseValue`,
`priceHint`,
`threeYearAverageReturn`,
`lastSplitDate`,
`lastSplitFactor`,
`legalType`,
`lastDividendDate`,
`morningStarOverallRating`,
`earningsQuarterlyGrowth`,
`priceToSalesTrailing12Months`,
`dateShortInterest`,
`pegRatio`,
`ytdReturn`,
`forwardPE`,
`lastCapGain`,
`shortPercentOfFloat`,
`sharesShortPriorMonth`,
`impliedSharesOutstanding`,
`category`,
`fiveYearAverageReturn`,
`previousClose`,
`regularMarketOpen`,
`twoHundredDayAverage`,
`trailingAnnualDividendYield`,
`payoutRatio`,
`volume24Hr`,
`regularMarketDayHigh`,
`navPrice`,
`averageDailyVolume10Day`,
`regularMarketPreviousClose`,
`fiftyDayAverage`,
`trailingAnnualDividendRate`,
`open`,
`toCurrency`,
`averageVolume10days`,
`expireDate`,
`algorithm`,
`dividendRate`,
`exDividendDate`,
`circulatingSupply`,
`startDate`,
`regularMarketDayLow`,
`currency`,
`trailingPE`,
`regularMarketVolume`,
`lastMarket`,
`maxSupply`,
`openInterest`,
`marketCap`,
`volumeAllCurrencies`,
`strikePrice`,
`averageVolume`,
`dayLow`,
`ask`,
`askSize`,
`volume`,
`fiftyTwoWeekHigh`,
`fromCurrency`,
`fiveYearAvgDividendYield`,
`fiftyTwoWeekLow`,
`bid`,
`tradeable`,
`dividendYield`,
`bidSize`,
`dayHigh`,
`regularMarketPrice`,
`preMarketPrice`,
`logo_url`,
`tradeDate`) VALUES (
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s,
%s, %s, %s,%s, %s, %s, %s, %s, %s,%s
)
""")
